# Generated by Django 4.2.21 on 2026-06-07 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerEconomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_coins', models.IntegerField(default=200)),
                ('inventory', models.JSONField(default=economy.models.default_inventory)),
                ('equipped_felt', models.CharField(default='felt_classic', max_length=50)),
                ('equipped_card_back', models.CharField(default='back_classic', max_length=50)),
                ('equipped_avatar_frame', models.CharField(default='frame_none', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='economy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
