# Generated by Django 4.2.21 on 2026-06-07 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hands_played', models.IntegerField(default=0)),
                ('total_chips', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('win_rate', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
