# Generated by Django 4.2.21 on 2026-06-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture uploaded by the user.', null=True, upload_to='avatars/'),
        ),
    ]
