# Generated by Django 5.2.12 on 2026-05-27 06:13

import tables.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_number', models.PositiveIntegerField()),
                ('pot_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('winners', models.JSONField()),
                ('community_cards', models.JSONField()),
                ('player_summary', models.JSONField(default=list)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hand_history',
                'ordering': ['hand_number'],
            },
        ),
        migrations.CreateModel(
            name='PokerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(default=tables.models.generate_invite_code, max_length=6, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('small_blind', models.DecimalField(decimal_places=2, max_digits=10)),
                ('big_blind', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_buy_in', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_buy_in', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_players', models.IntegerField(choices=[(2, '2'), (6, '6'), (9, '9')], default=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'poker_tables',
                'ordering': ['-created_at'],
            },
        ),
    ]
