# Generated by Django 5.2.12 on 2026-05-27 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pokertable',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='handhistory',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hand_history', to='tables.pokertable'),
        ),
        migrations.AlterUniqueTogether(
            name='handhistory',
            unique_together={('table', 'hand_number')},
        ),
    ]
